import Vue from "vue"
import VueRouter from "vue-router"
Vue.use(VueRouter)

export default new VueRouter({
	linkActiveClass:"active",
	mode:"history",
	routes:[
		{
			path:"/movie",
			component:() => import("@/views/movie"),
			meta:{
				title:"电影演出赛事"
			},
			children:[
				{
					path:"citylist",
					component:()=>import("@/components/CityList"),
					meta:{
						title:"当前城市"
					}
				},
				{
					path:"playing",
					component:()=>import("@/components/Playing"),
					meta:{
						title:"正在热映"
					}
				},
				{
					path:"upcoming",
					component:()=>import("@/components/UpComing"),
					meta:{
						title:"即将上映"
					}
				},
				{
					path:"search",
					component:()=>import("@/components/Search"),
					meta:{
						title:"搜索"
					}
				},
				{
					path:"detail/:movieId",
					components:{
						default:()=>import("@/components/Playing"),
						detail:()=>import("@/components/Detail")
					},
					props:{
						detail:true
					}
				},
				{
					path:"/movie",
					redirect:"playing"
				}
			]
		},
		{
			path:"/cinema",
			component: () => import("@/views/cinema"),
			meta:{
				title:"影院"
			}
		},
		{
			path:"/mine",
			component: () => import("@/views/mine"),
			meta:{
				title:"我的"
			}
		},
		{
			path:"/*",
			redirect:"/movie"
		}
	]
})