const friendList = {
    "workmate":{
        "category":"同事",
        "list":[
            {
                "name":"张三",
                "sex":"男",
            },
            {
                "name":"李四",
                "sex":"男"
            },
            {
                "name":"王五",
                "sex":"男"
            }
        ]
    },
    "netfrients":{
        "category":"网友",
        "list":[
            {
                "name":"小红",
                "sex":"女"
            },
            {
                "name":"王二",
                "sex":"男"
            },
            {
                "name":"郭采洁",
                "sex":"女",
            },
            {
                "name":"周杰伦",
                "sex":"男"
            }
        ]
    },
    "villager":{
        "category":"老乡",
        "list":[
            {
                "name":"小莉",
                "sex":"女"
            },
            {
                "name":"小李",
                "sex":"男"
            },
            {
                "name":"大锤",
                "sex":"男"
            }
        ]
    }
}